package com.zxx.core.model;

import java.io.Serializable;
import mboog.support.model.NoKey;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table log
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SysLog implements NoKey, Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.evt_datetime
     *
     * @mbg.generated
     */
    private String evtDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.evt_type
     *
     * @mbg.generated
     */
    private String evtType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.record
     *
     * @mbg.generated
     */
    private Integer record;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.source
     *
     * @mbg.generated
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.evt_id
     *
     * @mbg.generated
     */
    private String evtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.computer
     *
     * @mbg.generated
     */
    private String computer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.cat
     *
     * @mbg.generated
     */
    private String cat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.msg
     *
     * @mbg.generated
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.evt_datetime
     *
     * @return the value of log.evt_datetime
     *
     * @mbg.generated
     */
    public String getEvtDatetime() {
        return evtDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.evt_datetime
     *
     * @param evtDatetime the value for log.evt_datetime
     *
     * @mbg.generated
     */
    public void setEvtDatetime(String evtDatetime) {
        this.evtDatetime = evtDatetime == null ? null : evtDatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.evt_type
     *
     * @return the value of log.evt_type
     *
     * @mbg.generated
     */
    public String getEvtType() {
        return evtType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.evt_type
     *
     * @param evtType the value for log.evt_type
     *
     * @mbg.generated
     */
    public void setEvtType(String evtType) {
        this.evtType = evtType == null ? null : evtType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.record
     *
     * @return the value of log.record
     *
     * @mbg.generated
     */
    public Integer getRecord() {
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.record
     *
     * @param record the value for log.record
     *
     * @mbg.generated
     */
    public void setRecord(Integer record) {
        this.record = record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.source
     *
     * @return the value of log.source
     *
     * @mbg.generated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.source
     *
     * @param source the value for log.source
     *
     * @mbg.generated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.evt_id
     *
     * @return the value of log.evt_id
     *
     * @mbg.generated
     */
    public String getEvtId() {
        return evtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.evt_id
     *
     * @param evtId the value for log.evt_id
     *
     * @mbg.generated
     */
    public void setEvtId(String evtId) {
        this.evtId = evtId == null ? null : evtId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.computer
     *
     * @return the value of log.computer
     *
     * @mbg.generated
     */
    public String getComputer() {
        return computer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.computer
     *
     * @param computer the value for log.computer
     *
     * @mbg.generated
     */
    public void setComputer(String computer) {
        this.computer = computer == null ? null : computer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.cat
     *
     * @return the value of log.cat
     *
     * @mbg.generated
     */
    public String getCat() {
        return cat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.cat
     *
     * @param cat the value for log.cat
     *
     * @mbg.generated
     */
    public void setCat(String cat) {
        this.cat = cat == null ? null : cat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.msg
     *
     * @return the value of log.msg
     *
     * @mbg.generated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.msg
     *
     * @param msg the value for log.msg
     *
     * @mbg.generated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", evtDatetime=").append(evtDatetime);
        sb.append(", evtType=").append(evtType);
        sb.append(", record=").append(record);
        sb.append(", source=").append(source);
        sb.append(", evtId=").append(evtId);
        sb.append(", computer=").append(computer);
        sb.append(", cat=").append(cat);
        sb.append(", msg=").append(msg);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}