package com.zxx.core.service.impl;

import com.zxx.core.mapper.LogCountMapper;
import com.zxx.core.model.LogCount;
import com.zxx.core.model.LogCountExample;
import com.zxx.core.service.LogCountService;
import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import mboog.support.model.NoKey;
import mboog.support.service.ServiceSupport;
import org.springframework.stereotype.Service;

@Service
public class LogCountServiceImpl extends ServiceSupport<NoKey, LogCount, LogCountExample, LogCountMapper> implements LogCountService {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_count
     *
     * @mbg.generated
     */
    @Resource
    private LogCountMapper logCountMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_count
     *
     * @mbg.generated
     */
    @PostConstruct
    private void initService() {
        super.mapper = logCountMapper;
    }
}