package com.zxx.core.service.impl;

import com.zxx.core.mapper.SysLogTaskInfoMapper;
import com.zxx.core.model.SysLogTaskInfo;
import com.zxx.core.model.SysLogTaskInfoExample;
import com.zxx.core.service.SysLogTaskInfoService;
import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import mboog.support.model.NoKey;
import mboog.support.service.ServiceSupport;
import org.springframework.stereotype.Service;

@Service
public class SysLogTaskInfoServiceImpl extends ServiceSupport<NoKey, SysLogTaskInfo, SysLogTaskInfoExample, SysLogTaskInfoMapper> implements SysLogTaskInfoService {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_task
     *
     * @mbg.generated
     */
    @Resource
    private SysLogTaskInfoMapper sysLogTaskInfoMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_task
     *
     * @mbg.generated
     */
    @PostConstruct
    private void initService() {
        super.mapper = sysLogTaskInfoMapper;
    }
}